In [ ]:
# Create a list of 5 integers
nums = [5, 10, 15, 20, 25]
print("Original list:", nums)

# append
nums.append(30)
print("After append:", nums)

# extend
nums.extend([35, 40])
print("After extend:", nums)

# insert
nums.insert(2, 12)
print("After insert:", nums)

# remove
nums.remove(20)
print("After remove:", nums)

# pop
nums.pop()
print("After pop:", nums)

# index
print("Index of 15:", nums.index(15))

# count
print("Count of 10:", nums.count(10))

# sort
nums.sort()
print("After sort:", nums)

# reverse
nums.reverse()
print("After reverse:", nums)

# clear
nums.clear()
print("After clear:", nums)


Original list: [5, 10, 15, 20, 25]
After append: [5, 10, 15, 20, 25, 30]
After extend: [5, 10, 15, 20, 25, 30, 35, 40]
After insert: [5, 10, 12, 15, 20, 25, 30, 35, 40]
After remove: [5, 10, 12, 15, 25, 30, 35, 40]
After pop: [5, 10, 12, 15, 25, 30, 35]
Index of 15: 3
Count of 10: 1
After sort: [5, 10, 12, 15, 25, 30, 35]
After reverse: [35, 30, 25, 15, 12, 10, 5]
After clear: []


#### Example

In [ ]:
students=('Alice','Ben','Clara')
# Try To Change The Second Name
students[1]=('David')

#### What Happens?

In [ ]:
# We Will Get an Error:
TypeError: 'tuple' object does not support item assignment



#### Explanation:

In [ ]:
# Tuples in Python are immutable, which means their values cannot be changed after they are created. Once the tuple is defined, you cannot add, remove, or modify any of its elements. This is why trying to change the second name causes an error.

In [5]:
# Create a set with duplicate values
numbers = {1, 2, 3, 4, 2, 3, 5}
# Print the set
print(numbers)



{1, 2, 3, 4, 5}


#### Explanation:

In [ ]:
# A set in Python stores only unique values. When you create a set with duplicate numbers, Python automatically removes the duplicates.
# That’s why each number appears only once in the printed output.

In [6]:
# Create the dictionary
person = {
    'name': 'Alex',
    'age': 16,
    'city': 'New York'
}

# Update the age
person['age'] = 17

# Add a new key 'email'
person['email'] = 'alex@example.com'

# Print the final dictionary
print(person)


{'name': 'Alex', 'age': 17, 'city': 'New York', 'email': 'alex@example.com'}


In [8]:
# Take age as a variable
age = 18

# Check eligibility
if age >= 18:
    print(" eligible to vote.")
else:
    print(" not eligible to vote yet.")
# We can change the value of age to test different cases.

 eligible to vote.


In [9]:
# Given marks
marks = 82

# Determine the grade
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

# Print the grade
print("Grade:", grade)
# You can change the value of marks to see different results.


Grade: B


In [10]:
# Given number
num = 4

if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")
    # Change the value of num to test different cases.


The number is positive.
It is also even.


#### Section B:Numpy

In [11]:
import numpy as np

# Scalar
scalar = np.array(5)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
# or: np.arange(1, 6)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([10, 20, 30, 40, 50, 60]).reshape(2, 3)
# or: np.arange(10, 70, 10).reshape(2, 3)

# Print results
print("Scalar:", scalar)
print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)


Scalar: 5
1D Array:
 [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [12]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

# Print the array
print(random_array)
# This creates a 4×4 NumPy array with random integers from 0 to 100 (inclusive).


[[97 30 42 20]
 [51 67 98 39]
 [71 86  7 88]
 [21 37 89 40]]


In [13]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Convert to a Pandas DataFrame with column names
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

# Print the DataFrame
print(df)
# This creates a 3×3 DataFrame with columns A, B, and C.


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [14]:
import pandas as pd
import numpy as np

# Create a small DataFrame manually
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jane'],
    'Age': [25, 30, 22, 28, 35, 40, 30, 28, 22, 35],
    'City': ['NY', 'LA', 'NY', 'Chicago', 'LA', 'NY', 'Chicago', 'LA', 'NY', 'LA'],
    'Salary': [50000, 60000, np.nan, 55000, 70000, 80000, np.nan, 65000, 50000, 70000]
}

df = pd.DataFrame(data)

# Display DataFrame info
print("Info:")
print(df.info(), "\n")

# Describe the DataFrame (numerical columns)
print("Describe:")
print(df.describe(), "\n")

# Select 'Name' and 'City' columns
print("Name and City columns:")
print(df[['Name', 'City']], "\n")

# Drop 'City' column
df_dropped = df.drop('City', axis=1)
print("After dropping 'City':")
print(df_dropped, "\n")

# Fill missing values in 'Salary' with mean
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print("After filling missing Salary with mean:")
print(df, "\n")

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("After removing duplicates:")
print(df_no_duplicates)


Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None 

Describe:
             Age        Salary
count  10.000000      8.000000
mean   29.500000  62500.000000
std     5.854723  10690.449676
min    22.000000  50000.000000
25%    25.750000  53750.000000
50%    29.000000  62500.000000
75%    33.750000  70000.000000
max    40.000000  80000.000000 

Name and City columns:
      Name     City
0    Alice       NY
1      Bob       LA
2  Charlie       NY
3    David  Chicago
4      Eva       LA
5    Frank       NY
6    Grace  Chicago
7   Hannah       LA
8      Ian       NY
9     Jane       LA 

After dropping 'City':
      Name  Age   Salary
0    Alice   

/tmp/ipython-input-3735662177.py:33: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)
