#### Data Preprocessing

In [1]:
# Load the Dataset
import pandas as pd

# Load dataset
df = pd.read_csv("anime.csv")


In [2]:
print(df)

       anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      

In [3]:
print("\nColumn Names:")
print(df.columns)



Column Names:
Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')


In [4]:
# Handle Missing Values
print("\nMissing values in each column:")
print(df.isnull().sum())

# Remove rows with missing values
df = df.dropna()

print("\nDataset shape after handling missing values:", df.shape)



Missing values in each column:
anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

Dataset shape after handling missing values: (12017, 7)


In [5]:
# Fill missing categorical values
df['genre'].fillna('Unknown', inplace=True)
df['type'].fillna('Unknown', inplace=True)

# Fill missing numerical values
df['rating'].fillna(df['rating'].mean(), inplace=True)

print("\nMissing values after handling:")
print(df.isnull().sum())



Missing values after handling:
anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64


/tmp/ipython-input-2129583830.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['genre'].fillna('Unknown', inplace=True)
/tmp/ipython-input-2129583830.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using '

In [6]:
# dataset Exploration
print("\nDataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())



Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 12017 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12017 non-null  int64  
 1   name      12017 non-null  object 
 2   genre     12017 non-null  object 
 3   type      12017 non-null  object 
 4   episodes  12017 non-null  object 
 5   rating    12017 non-null  float64
 6   members   12017 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 751.1+ KB
None

Statistical Summary:
           anime_id        rating       members
count  12017.000000  12017.000000  1.201700e+04
mean   13638.001165      6.478264  1.834888e+04
std    11231.076675      1.023857  5.537250e+04
min        1.000000      1.670000  1.200000e+01
25%     3391.000000      5.890000  2.250000e+02
50%     9959.000000      6.570000  1.552000e+03
75%    23729.000000      7.180000  9.588000e+03
max    34519.000000     10.000000  1.013917e+06


#### Feature Extraction

In [7]:
# Convert Categorical data into numerical form
# One-hot encoding for genre
genre_features = df['genre'].str.get_dummies(sep=', ')

# One-hot encoding for type
type_features = pd.get_dummies(df['type'])

print("\nGenre feature matrix shape:", genre_features.shape)
print("Type feature matrix shape:", type_features.shape)



Genre feature matrix shape: (12017, 43)
Type feature matrix shape: (12017, 6)


In [8]:
# Normalize numerical features
from sklearn.preprocessing import StandardScaler
import numpy as np

# Convert 'episodes' column to numeric (Unknown → NaN)
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

print("Episodes column converted to numeric.")
print("Missing values after conversion:")
print(df[['episodes', 'rating', 'members']].isnull().sum())

# Fill missing values with column mean
df['episodes'].fillna(df['episodes'].mean(), inplace=True)
df['rating'].fillna(df['rating'].mean(), inplace=True)
df['members'].fillna(df['members'].mean(), inplace=True)

print("\nMissing values handled successfully!")

# Select numerical features
numerical_features = df[['episodes', 'rating', 'members']]

# Normalize numerical features
scaler = StandardScaler()
numerical_scaled = scaler.fit_transform(numerical_features)

print("\nNumerical features normalized successfully!")
print("Scaled feature sample:")
print(numerical_scaled[:5])


Episodes column converted to numeric.
Missing values after conversion:
episodes    187
rating        0
members       0
dtype: int64

Missing values handled successfully!

Numerical features normalized successfully!
Scaled feature sample:
[[-0.24582493  2.82447359  3.2920442 ]
 [ 1.10242408  2.7170322  14.00240972]
 [ 0.82421397  2.70726481  1.73221578]
 [ 0.24639296  2.62912562 11.83349907]
 [ 0.82421397  2.61935822  2.40051759]]


/tmp/ipython-input-1864037581.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['episodes'].fillna(df['episodes'].mean(), inplace=True)
/tmp/ipython-input-1864037581.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=Tr

In [10]:
# Final Feature Matrix
import numpy as np

feature_matrix = np.hstack((
    genre_features.values,
    type_features.values,
    numerical_scaled
))

print("\nFinal Feature Matrix Shape:", feature_matrix.shape)



Final Feature Matrix Shape: (12017, 52)


#### Recommendation system using cosine similarity

In [12]:
# Compute Cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(feature_matrix)

print("\nCosine Similarity Matrix created")
print("Cosine Similarity Matrix Shape:", cosine_sim.shape)



Cosine Similarity Matrix created
Cosine Similarity Matrix Shape: (12017, 12017)


In [13]:
# Recommendation Function
def recommend_anime(anime_name, top_n=5, threshold=0.5):
    if anime_name not in df['name'].values:
        print("Anime not found in dataset")
        return

    anime_index = df[df['name'] == anime_name].index[0]

    similarity_scores = list(enumerate(cosine_sim[anime_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    filtered_scores = [
        score for score in similarity_scores
        if score[1] >= threshold and score[0] != anime_index
    ]

    print(f"\nTop {top_n} anime recommendations for '{anime_name}':\n")

    for i, score in filtered_scores[:top_n]:
        print(f"{df.iloc[i]['name']}  --> Similarity Score: {score:.2f}")


In [14]:
# Example recommendation
recommend_anime("Naruto", top_n=5, threshold=0.6)



Top 5 anime recommendations for 'Naruto':

Fairy Tail  --> Similarity Score: 0.98
Bleach  --> Similarity Score: 0.96
Hunter x Hunter (2011)  --> Similarity Score: 0.96
D.Gray-man  --> Similarity Score: 0.96
Soul Eater  --> Similarity Score: 0.94


#### Threshold Experimentation

In [ ]:
#| Threshold Value | Recommendation Count | Quality       |
#| --------------- | -------------------- | ------------- |
#| 0.4             | High                 | Less accurate |
#| 0.6             | Medium               | Balanced      |
#| 0.8             | Low                  | Very accurate |


In [ ]:
# Performance Analysis & Improvements:

# Strengths:
#Fast and scalable
#No user interaction data required
#Effective for content-rich datasets

#Limitations:
#No personalization
#Cold-start problem
#Genre dominance

#Improvements:
#Hybrid model (content + collaborative)
#TF-IDF for genres
#Add popularity weighting
#Use matrix factorization



#### Interview Questions

In [ ]:
#| User-Based                          | Item-Based               |
#| ----------------------------------- | ------------------------ |
#| Finds similar users                 | Finds similar items      |
#| Recommends what similar users liked | Recommends similar anime |
#| Slower for large users              | Faster and scalable      |
#| Less stable                         | More stable              |


In [ ]:
#Collaborative Filtering is a recommendation technique that predicts user preferences based on similarity patterns between users or items.

#Working:
#Collect interaction data
#Compute similarity
#Recommend based on similarity

#In this assignment:
#Items = Anime
#Similarity = Cosine similarity
#Features = Genre, Rating, Episodes, Members